### ISSUE TITLE
［依頼］ＣｈａｔーＳｐａｃｅの挙動確認

### ISSUE THREAD

**Issue by CCCP1994** [CCCP1994/chat-space#20]
＃ＩＰアドレス：
１８．１８０．４０．６０
18.180.40.60

**Comment by yasunamiura** [comment]
山本さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

- メッセージ同士の余白を整えましょう(上下左右)
- EDITの文字色を水色にしましょう
[![Image from Gyazo](https://i.gyazo.com/1c3455e7272cacef12a698b6ca91b190.png)](https://gyazo.com/1c3455e7272cacef12a698b6ca91b190)
見本
[![Image from Gyazo](https://i.gyazo.com/3d9cf934fcac58952f556d4d0ac30785.png)](https://gyazo.com/3d9cf934fcac58952f556d4d0ac30785)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by CCCP1994** [comment]
先程指摘された二箇所を修正しましたので、コミットして１８．１８０．４０．６０上にｐｕｌｌしておきました。

**Comment by miyu-yamamoto** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
